
import React from 'react';

export const DeploymentSection: React.FC = () => {
  return (
    <section className="bg-slate-800/50 rounded-lg p-6 shadow-lg border border-slate-700">
      <div className="flex justify-between items-center border-b border-slate-600 pb-2 mb-4">
        <div>
           <h2 className="text-2xl font-semibold text-white">
            Deployment & Demo
            </h2>
            <p className="text-sm text-slate-400">
                Visualizing the final output on a public landing page.
            </p>
        </div>
         <div className="bg-slate-700 text-slate-300 text-sm font-bold px-3 py-1 rounded-full">
            CONCEPT
        </div>
      </div>
      
      <div className="space-y-4">
        <p className="text-slate-300">
            After a song is generated by the pipeline (e.g., <code className="font-mono bg-slate-700 px-1.5 py-0.5 rounded-md text-sm text-cyan-300">song_20240101_120000.wav</code>), the final step is to make it accessible. The project plan specifies using <a href="https://carrd.co/" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">Carrd.co</a> for a simple, elegant landing page.
        </p>

        <div className="bg-slate-900/70 p-6 rounded-lg border border-slate-700">
            <h3 className="text-lg font-semibold text-white mb-4">Carrd.co Demo Player Mock-up</h3>
            <div className="bg-white/10 p-4 rounded-lg flex items-center space-x-4">
                {/* Play Button */}
                <button 
                    className="w-12 h-12 flex-shrink-0 bg-cyan-500 rounded-full flex items-center justify-center text-white hover:bg-cyan-600 transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-slate-800 focus:ring-cyan-500"
                    aria-label="Play demo song"
                >
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6 ml-1">
                        <path fillRule="evenodd" d="M4.5 5.653c0-1.426 1.529-2.33 2.779-1.643l11.54 6.647c1.295.742 1.295 2.545 0 3.286L7.279 20.99c-1.25.717-2.779-.217-2.779-1.643V5.653Z" clipRule="evenodd" />
                    </svg>
                </button>
                {/* Track Info and Progress Bar */}
                <div className="flex-grow">
                    <p className="font-semibold text-white">"Lost Love Pop"</p>
                    <p className="text-sm text-slate-300">Prompt: upbeat pop about lost love</p>
                    <div className="w-full bg-slate-600 rounded-full h-1.5 mt-2">
                        <div className="bg-cyan-400 h-1.5 rounded-full" style={{ width: '25%' }}></div>
                    </div>
                </div>
            </div>
             <p className="text-xs text-slate-500 mt-3 text-center">
                This player would be embedded on the Carrd.co page, using their "Pro" plan features for audio uploads.
            </p>
        </div>
      </div>
    </section>
  );
};
